default: &default
  adapter: postgresql
  encoding: unicode
  database: use_index
  pool: 5
  username: postgres
  password:
  host: localhost

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
