# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad3c8d2842f7a330d39f86673f31012d1e4b0f571fdce7182ace342fc96ea052ba2d8d279f8a062574fc07b4fcfd437171b3d9953d2c4f14c232372d10f9b8f0

test:
  secret_key_base: 8fc8f36eeb2c8dd88486934435a526311ec13bbdc4b2ba5dfc43960db985e5002e6f6e57893aa96302de6b28611cecb5d15ae33613c9c79f2881d16d84670121

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ba3b61a73eb87cd2ac94b1e22dd758b341918ba1028fa7438c1e5269995e2327f2233180c0ce00d95a60649727b822a8141fe4ac1f16383f0932287d4ffe4109
